apiVersion: v1
kind: Pod
metadata:
  labels:
    test: readiness-exec
  name: readiness-exec
spec:
  containers:
  - name: readyornot
    image: busybox
    command:
      - sleep
      - "3600"
    readinessProbe:
      exec:
        command:
        - wget
        - https://192.168.49.2:8443/healthz
      initialDelaySeconds: 3
      periodSeconds: 3

