apiVersion: v1
kind: Pod
metadata:
  name: cm-to-pod-volume
spec:
  containers:
    - name: test-container
      image: registry.k8s.io/busybox
      command: [ "/bin/sh", "-c","sleep 3600","ls /etc/config/" ]
      volumeMounts:
      - name: config-volume
        mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        # Provide the name of the ConfigMap containing the files you want
        # to add to the container
        name: cm-data-to-pod-volume
  restartPolicy: Never
