apiVersion: v1
kind: Pod
metadata:
    name: dapi-test-pod
spec:
     containers:
       - name: test-container
         image: registry.k8s.io/busybox
         command: [ "/bin/sh", "-c", "sleep 3600" ]
         env:
           # Define the environment variable
           - name: SUN_SHINE_KEY
             valueFrom:
               configMapKeyRef:
                 # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
                 name: cm-to-pod
                 # Specify the key associated with the value
                 key: color.sun
     restartPolicy: Never
   
